# Generated by Django 6.1.1 on 2026-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(blank=True)),
                ('is_now_showing', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
