# Generated by Django 6.1.1 on 2026-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_city_cinema_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
