# Generated by Django 6.1.1 on 2026-09-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.cinema')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('cinema', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.showtime')),
                ('seats', models.ManyToManyField(related_name='bookings', to='movies.seat')),
            ],
            options={
                'ordering': ['-booking_time'],
            },
        ),
    ]
