# Generated by Django 6.1.1 on 2026-09-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_moviereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='review_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
