# Generated by Django 6.1.1 on 2026-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('luxury', 'Luxury / Recliner')], default='normal', max_length=20),
        ),
    ]
